setup:
  simtype: grb  # grb -> src+bkg; bkg -> empty fields
  runid: run0406_ID000126  # can be null; all; or any template 
  trials: 1  # realisations per runid
  start_count: 0  # starting count for seed

simulation:
  caldb: prod3b  # calibration database
  irf: South_z40_average_100s  # istrument response function
  tobs: 100  # total obs time (s)
  onset: 0  # time of bkg only a.k.a. delayed onset of burst (s)
  emin: 0.03  # simulation minimum energy (TeV)
  emax: 150  # simulation maximum energy (TeV)
  roi: 2.5  # region of interest radius (deg)

options:
  set_ebl: True  # uses the EBL absorbed template
  ebl: gilmore_tau_fiducial.csv

path: 
  data: $DATA  # all data should be under this folder
  ebl: $DATA/ebl_table

