channels:
  - conda-forge
  - cta-observatory
dependencies:
  - python=3.7
  - ctools=1.7.4
  - astropy
  - healpy
  - pandas
  - xml
  - pyaml
  - scipy
  - pyregion
  - seaborn
#  - untangle  # required ONLY by the old version of the pipeline (folder "thesis")